import { useState } from 'react';
import { ExternalLink, Loader } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../../../components/ui/dialog';
import { Button } from '../../../../components/ui/button';
import { Input } from '../../../../components/ui/input';
import { Label } from '../../../../components/ui/label';
import { PROVIDERS } from '../../../../api/recruiter/integrations';

/**
 * Collects the customer's own ATS API key.
 *
 * Only half the handshake: this key lets TruDev call the ATS. The other half —
 * the key the ATS uses to call TruDev — is generated by the server and shown
 * once on success. The copy says so up front, because a recruiter who thinks
 * they are done after this step will have a silently half-connected
 * integration.
 */
export function ConnectDialog({ provider, open, onOpenChange, onSubmit, submitting }) {
  const [apiKey, setApiKey] = useState('');
  const [error, setError] = useState('');
  const meta = PROVIDERS[provider] || { label: provider };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!apiKey.trim()) {
      setError(`Enter your ${meta.label} API key.`);
      return;
    }
    setError('');
    try {
      await onSubmit(apiKey.trim());
      setApiKey('');
    } catch (err) {
      setError(err?.message || `Could not connect to ${meta.label}.`);
    }
  };

  const handleOpenChange = (next) => {
    if (!next) {
      setApiKey('');
      setError('');
    }
    onOpenChange(next);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Connect {meta.label}</DialogTitle>
          <DialogDescription>
            Connecting takes two keys. Paste yours below, and we&apos;ll give you
            one to paste back into {meta.label}.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="mt-5 flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <Label htmlFor="ats-api-key" className="text-[13px] font-medium text-text-primary">
              {meta.credentialLabel || `${meta.label} API key`}
            </Label>
            <Input
              id="ats-api-key"
              type="password"
              autoComplete="off"
              spellCheck={false}
              value={apiKey}
              onChange={(event) => setApiKey(event.target.value)}
              placeholder="Paste your API key"
              className="font-mono text-[13px]"
            />
            {meta.credentialHint && (
              <p className="text-[12.5px] leading-[17px] text-text-secondary">
                {meta.credentialHint}
              </p>
            )}
          </div>

          {error && (
            <p role="alert" className="text-[13px] text-error">
              {error}
            </p>
          )}

          <DialogFooter className="mt-1 justify-between">
            {meta.docsUrl ? (
              <a
                href={meta.docsUrl}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1.5 text-[13px] text-text-secondary transition-colors hover:text-text-primary"
              >
                Setup guide
                <ExternalLink className="h-[13px] w-[13px]" />
              </a>
            ) : (
              <span />
            )}
            <div className="flex items-center gap-2">
              <Button
                type="button"
                variant="ghost"
                onClick={() => handleOpenChange(false)}
                className="h-[38px] px-3 text-[13px]"
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={submitting}
                className="h-[38px] gap-2 px-4 text-[13px]"
              >
                {submitting && <Loader className="h-[14px] w-[14px] animate-spin" />}
                Connect
              </Button>
            </div>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
